version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./www:/var/www
        depends_on:
            - php
    php:
        image: php-fpm:7.4
        build: ./docker/images/php
        volumes:
            - ./www:/var/www
    mysql:
        image: mysql       
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
            - ./docker/import:/docker-entrypoint-initdb.d
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
